CREATE TABLE Cities(
	
	CityId INT PRIMARY KEY NOT NULL,
	CityName NVARCHAR(MAX) NOT NULL


);
CREATE TABLE Areas(
	AreaId INT PRIMARY KEY NOT NULL ,
	AreaName NVARCHAR(MAX) NOT NULL,
	CityId INT FOREIGN KEY REFERENCES Cities(CityId)




);